/* Generated By:JavaCC: Do not edit this line. htmlConstants.java */
package egtry.html;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface htmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int CAP = 9;
  /** RegularExpression Id. */
  int EPSILON = 10;
  /** RegularExpression Id. */
  int NewLine = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"/\"",
    "\":\"",
    "\".\"",
    "<NUM>",
    "<ID>",
    "<CAP>",
    "<EPSILON>",
    "<NewLine>",
    "\"ADD\"",
    "\"IMAGE\"",
    "\"WITH\"",
    "\"SOURCE\"",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"AND\"",
    "\"TEXT\"",
    "\"COLOR\"",
    "\"FONT\"",
    "\"\\\"\"",
    "\"_\"",
  };

}
