/* Generated By:JavaCC: Do not edit this line. htmlConstants.java */
package egtry.Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface htmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EPSILON = 4;
  /** RegularExpression Id. */
  int NewLine = 5;
  /** RegularExpression Id. */
  int alphanumeric = 6;
  /** RegularExpression Id. */
  int sentence = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<EPSILON>",
    "<NewLine>",
    "<alphanumeric>",
    "<sentence>",
    "\"ADD \"",
    "\"IMAGE \"",
    "\"WITH \"",
    "\"SOURCE \"",
    "\"HEADING \"",
    "\"PARAGRAPH \"",
    "\"LINK \"",
    "\"AND \"",
    "\"TEXT \"",
    "\"COLOR \"",
    "\"FONT \"",
    "\"\\\"\"",
  };

}
